src/force-app/main/default/objects/LWCPagination__c/LWCPagination__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>LWC Pagination</label>
</CustomObject>

src/force-app/main/default/objects/LWCPagination__c/fields/PageSize__c.field-meta.xml
<CustomField>
    <fullName>PageSize__c</fullName>
    <defaultValue>25</defaultValue>
    <label>Page Size</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

src/force-app/main/default/classes/tests/TestCustomSettingsService.cls
@IsTest
public with sharing class TestCustomSettingsService {
    @IsTest
    private static void capturePreferredLWCPaginationPageSizeTest() {
        fflib_ApexMocks mocks = new fflib_ApexMocks();
        CustomSettingsSelector selectorMock = (CustomSettingsSelector)mocks.mock(CustomSettingsSelector.class);
        CustomSettingsSelector.instance = selectorMock;
        LWCPagination__c settings = new LWCPagination__c();
        Integer pageSize = Constants.LWC_PAGINATION_PAGE_SIZE_DEFAULT * 4;
        //Stub data.
        mocks.startStubbing();
        mocks.when(selectorMock.getLWCPaginationSettings()).thenReturn(settings);
        mocks.stopStubbing();
        CustomSettingsService.getInstance().capturePreferredLWCPaginationPageSize(pageSize);
        System.assertEquals(pageSize, LWCPagination__c.getInstance().PageSize__c);
    }
}