src/force-app/main/default/objects/LWCPagination__c/LWCPagination__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>LWC Pagination</label>
</CustomObject>

src/force-app/main/default/objects/LWCPagination__c/fields/PageSize__c.field-meta.xml
<CustomField>
    <fullName>PageSize__c</fullName>
    <defaultValue>25</defaultValue>
    <label>Page Size</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

src/force-app/main/default/classes/services/CustomSettingsService.cls
/**
 * @description OrderSelector: Service to capture Custom Settings-related Business logic.
 */
public with sharing class CustomSettingsService {
    @TestVisible
    private static CustomSettingsService instance;

    public static CustomSettingsService getInstance() {
        if (instance == null) {
            instance = new CustomSettingsService();
        }
        return instance;
    }

    public void capturePreferredLWCPaginationPageSize(Integer pageSize) {
        LWCPagination__c settings = CustomSettingsSelector.getInstance().getLWCPaginationSettings();
        settings.PageSize__c = pageSize;
        upsert settings;
    }
}